### ISSUE TITLE
RunIssue

### ISSUE THREAD

**Issue by AhmedRamadanAhmed** [Decad/github-downloader#1]
I have win 10, i run this script on it ,but it gives me 
Exporting https://github.com/AhmedRamadanAhmed/Timer/trunk/CompetitiveProgramming
./git.sh: line 25: svn: command not found
When I write on git bash 
 chmod +x git.sh
./git.sh or 
./git.sh https://github.com/AhmedRamadanAhmed/Timer/tree/master/CompetitiveProgramming^C

**Comment by AhmedRamadanAhmed** [comment]
Closes#1

**Comment by ghost** [comment]
whaaaaat?
